version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS:-password}
      MONGO_INITDB_DATABASE: ${MONGODB_DB:-vector_db}
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  vector-db-api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - COHERE_API_KEY=${COHERE_API_KEY:-your_key_here}
      - COHERE_EMBED_URL=${COHERE_EMBED_URL:-https://api.cohere.ai/v1/embed}
      - COHERE_MODEL=${COHERE_MODEL:-embed-english-v3.0}
      - API_HOST=${API_HOST:-0.0.0.0}
      - API_PORT=${API_PORT:-8000}
      - MONGODB_URI=mongodb://${MONGODB_USER:-admin}:${MONGODB_PASS:-password}@mongodb:27017/vector_db?authSource=admin
      - MONGODB_DB=${MONGODB_DB:-vector_db}
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${API_HOST:-0.0.0.0}:${API_PORT:-8000}/v1/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data: 